config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :posts do
    resources :comments, only: [:create]
  end

  resources :articles do
    resources :comments, only: [:create]
  end

  resources :comments, only: [:show, :edit, :update, :destroy]
  resources :tags, only: [:show]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include FindingAllTags

  def home
    @entries = [] # Array of hashes
    @tags_hash = Hash.new(0)
    @content = ContentView.all

    @content.each do |content|
      content.tag_ids.each do |tag|
        @tags_hash[tag] += 1
      end
    end

    @tags.each do |tag|
      # Get current tag's font size
      css_class =
        case @tags_hash[tag.id]
        when 0..(@content.count / 8) then 'sm'
        when (@content.count / 8 + 1)..(@content.count / 7) then 'nm'
        else 'big'
        end

      @entries << { tag: tag, css_class: css_class }
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.slim
h1 = t :project_name
h2 = t :project_desc

h2
  = link_to t('go', name: 'the posts'), posts_path
h2
  = link_to t('go', name: 'the articles'), articles_path

- unless @entries.empty?
  h1 = t :tag_cloud
  .jumbotron
    .container
      .row
        .col-sm-10.col-sm-offset-1
          #tag_cloud
            - @entries.each do |entrie|
              span class="#{entrie[:css_class]}"
                = link_to entrie[:tag].name, entrie[:tag]