config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :posts do
    resources :comments, only: [:create]
  end

  resources :articles do
    resources :comments, only: [:create]
  end

  resources :comments, only: [:show, :edit, :update, :destroy]
  resources :tags, only: [:show]
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  author_name      :string
#  content          :text
#  commentable_id   :integer
#  commentable_type :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true, touch: true

  default_scope -> { order(created_at: :desc) }

  validates :author_name, length: { maximum: 65 }
  validates :content, presence: true
  validates :commentable_type, inclusion: { in: %w(Article Post) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @commentable = find_commentable
    @comment = @commentable.comments.build comment_params

    if @comment.save
      # get a channel name (post4, article2, etc.)
      path = request.path.split('/')
      channel = path[1] + path[2]

      # render html for JS append
      html = render @comment, layout: false
      Pusher[channel].trigger 'comments/create', html
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to @comment.commentable
    else
      render 'edit'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id]).destroy
    redirect_to @comment.commentable
  end

  private

    def find_commentable
      resource, id = request.path.split('/')[1, 2]
      resource.singularize.classify.constantize.find(id)
    end

    def comment_params
      params.require(:comment).permit(:author_name, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.media style="display: none;"
  .media-body
    h4 class="media-heading"
      = comment.author_name

      small   Posted #{time_ago_in_words(comment.created_at)} ago.
      small = link_to t('actions.show'), comment
      small = link_to t('actions.edit'), edit_comment_path(comment)
      small
        = link_to t('actions.delete'), comment, method: :delete,
            data: { confirm: t('actions.sure') }
    = comment.content

app/views/comments/_form.html.slim
= form_for([commentable, Comment.new], remote: true) do |f|
  = f.label t 'entry.author_name'
  = f.text_field :author_name, class: 'form-control'

  = f.label 'entry.content'
  = f.text_area :content, class: 'form-control'

  = f.submit "Submit", class: "btn btn-primary"

app/views/comments/edit.html.slim
h2
  = link_to t('go', name: 'the index'), root_url

= form_for (@comment) do |f|
    = f.label t 'entry.author_name'
    = f.text_field :author_name, class: 'form-control'

    = f.label t 'entry.content'
    = f.text_area :content, class: 'form-control'

    = f.submit "Submit", class: "btn btn-primary"

app/views/comments/show.html.slim
h2
  = link_to t('go', name: 'the index'), root_url

.container
  .row
    .col-md-8.col-md-offset-2
      .well
        .media
          .media-body
            h4 class="media-heading"
              = @comment.author_name

              small   Posted #{time_ago_in_words(@comment.created_at)} ago.
              small = link_to t('actions.show'), @comment
              small = link_to t('actions.edit'), edit_comment_path
              small
                = link_to t('actions.delete'), @comment, method: :delete,
                    data: { confirm: t('actions.sure') }
            = @comment.content